spring:
  application:
        name : spring-auth
  datasource:
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        driverClassName: org.h2.Driver
  security:
    enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
server:
  port: 8082

jwt:
  secret: hsdjkskdjskdlkds

